from enum import Flag, auto


class IdentityIssuer(Flag):
    SSP = auto()
    DETRAN = auto()
    CONS_REG_ECONOMIA = auto()
    MIN_EXERCITO = auto()
    OAB = auto()
    CREA = auto()
    SJS = auto()
    CTPS = auto()
    CREME = auto()
    MINEX = auto()
    CRM = auto()
    SJTC = auto()
    MAER = auto()
    DPF = auto()
    RBF = auto()
    IML = auto()
    CPROF = auto()
    CRO = auto()
    CRC = auto()
    DPMAF = auto()
    ME = auto()
    BM = auto()
    AERON = auto()
    SJT = auto()
    COREN = auto()
    DETRA = auto()
    EXERC = auto()
    SSI = auto()
    MINISTERIO_DA_MARINHA = auto()
    CRA_CONSELHO_ADMINISTRATIVO = auto()
    INSTITUTO_FELIX_PACHECO = auto()
    INST_NAC_PROPRIEDADE_INDUSTRIA = auto()
    MINISTERIO_DA_FAZENDA = auto()
    TRIBUNAL_REGIONAL_DO_TRABALHO = auto()
    CONSELHO_REGIONAL_PSICOLOGIA = auto()
    POLICIA_MILITAR = auto()
