from enum import Flag, auto


class Profession(Flag):
    ACOUGUEIRO = auto()  # Açougueiro
    ACUMPURISTA = auto()  # Acumpurista
    ADESTRADOR = auto()  # Adestrador/Tratador de Animais/Treinador de Animais
    ADMINISTRADOR = auto()  # Administrador
    ADVOGADO = auto()  # Advogado
    AEROVIARIO = auto()  # Aeroviario/Empregado de Aeroporto
    AFIADOR = auto()  # Afiador
    AGENCIADOR_DE_PROPAGANDA = auto()  # Agenciador de Propaganda
    AGENCIADOR_CARGAS_TRANSPORTES = auto()  # Agenciador de Serv. (Cargas/Transportes)
    AGENTE_ADMINISTRATIVO = auto()  # Agente Administrativo
    AGENTE_DE_COMPRA_VENDA = auto()  # Agente de Compra e Venda
    AGENTE_DE_SERVICOS_FUNERARIOS = auto()  # Agente de Serviços Funerarios
    AGENTE_DE_VIAGEM = auto()  # Agente de viagem/Agente de turismo/Operador de turismo
    AGRONOMO = auto()  # Agronomo
    AJUDANTE_GERAL = auto()  # Ajudante Geral
    AJUSTADOR_RETIFICADOR = auto()  # Ajustador/Retificador
    ALFAIATE = auto()  # Alfaiate
    AMBULANTES = auto()  # Ambulantes(Camelo,Pipoqueiro,etc)
    ANALISTA_RECURSOS_HUMANOS = auto()  # Analista de Cargos/Recursos Humanos etc
    ANALISTA_CREDITO_E_COBRANCA = auto()  # Analista de Cred/Cad/Cobr/Garant/Inf etc
    ANALISTA_CUSTOS_PROJ_SERV_ECONOMIA = auto()  # Analista de Custos/Proj/Serv/Economia etc
    ANALISTA_PRODUCAO_CRONOALISTA = auto()  # Analista de Producao/Cronoalista
    ANALISTA_SISTEMAS = auto()  # Analista de Sistemas
    APOSENTADO = auto()  # Aposentado(exceto funcionario publico)
    ARBITRO_DE_ESPORTES = auto()  # Arbitro de Esportes
    ARMADOR_DE_FERRAGENS = auto()  # Armador de Ferragens
    ARMEIRO = auto()  # Armeiro
    ARQUEOLOGO = auto()  # Arqueologo
    ARQUITETO = auto()  # Arquiteto
    ARQUIVISTA = auto()  # Arquivista
    ARTESAO = auto()  # Artesao
    ARTISTA_PLASTICO = auto()  # Artista Plastico
    ASCENSORISTA = auto()  # Ascensorista
    ASSISTENTE_SOCIAL = auto()  # Assistente Social
    ASTRONOMO = auto()  # Astronomo
    ATLETA = auto()  # Atleta Profissional
    ATOR = auto()  # Ator
    ATUARIO = auto()  # Atuario
    AUDITOR_PUBLICO = auto()  # Auditor Publico
    AUXILIAR_COZINHA_LIMPEZA_COSTURA_COPA = auto()  # Auxiliar Cozinha/Limpeza/Costura/Copa etc
    AUXILIAR_DE_ENFERMAGEM_TECNICO = auto()  # Auxiliar de Enfermagem/Tecnico de Enfermagem
    AUXILIAR_DE_ESCRITORIO = auto()  # Auxiliar de Escritorio e Ass.
    AUXILIAR_DE_LABORATORIO = auto()  # Auxiliar de Laboratorio
    AUXILIAR_DE_SERVICOS_GERAIS = auto()  # Auxiliar de Serviços Gerais
    AVALIADOR = auto()  # Avaliador
    CUIDADOR = auto()  # Cuidador
    DANCARINO = auto()  # Dançarino
    BANCARIO = auto()  # Bancario
    BARBEIRO = auto()  # Barbeiro
    BARISTA = auto()  # Barista/Barman/Barwoman
    BIBLIOTECARIO = auto()  # Bibliotecario
    BILHETEIRO_COBRADOR = auto()  # Bilheteiro(Transp/Diversao)/Trocador/Cobrador Transp Passageiro/Caixa
    BIOLOGO = auto()  # Biologo
    BIOMEDICO = auto()  # Biomedico
    BOLSISTA = auto()  # Bolsista
    BOMBEIRO_ENCANADOR = auto()  # Bombeiro/Encanador
    BORRACHEIRO = auto()  # Borracheiro
    CABELEIREIRO = auto()  # Cabeleireiro
    CAIXEIRO_VIAJANTE = auto()  # Caixeiro-Viajante
    CAMAREIRA_ARRUMADEIRA = auto()  # Camareira/Arrumadeira
    CANTOR = auto()  # Cantor
    CARGOS_DE_CONFIANCA_COMISSOES = auto()  # Cargos de Confiança/Comissoes
    CARREGADOR = auto()  # Carregador
    CARTEIRO = auto()  # Carteiro
    CARTORARIO = auto()  # Cartorario
    CASEIRO = auto()  # Caseiro
    CAVALARICO = auto()  # Cavalarico/Ferrador/Tratador de Animais
    CENOGRAFO = auto()  # Cenografo
    CHAVEIRO = auto()  # Chaveiro
    CHEFE_DA_PRODUCAO = auto()  # Chefe da Producao
    CHEFE_INTERMEDIARIO = auto()  # Chefe Intermediario
    COBRADOR_EM_GERAL = auto()  # Cobrador em Geral
    COMANDANTE_DE_EMBARCACOES = auto()  # Comandante de Embarcacoes
    COMENTARISTA = auto()  # Comentarista
    COMISSARIO_DE_BORDO = auto()  # Comissario de Bordo
    COMPOSITOR = auto()  # Compositor
    COMUNICOLOGO = auto()  # Comunicologo
    CONSELHEIRO_TUTELAR = auto()  # Conselheiro Tutelar
    CONSULTOR_DE_EMPRESAS = auto()  # Consultor de Empresas
    CONTADOR = auto()  # Contador
    CONTRAMESTRE = auto()  # Contramestre
    CONTROLADOR_DE_VOO = auto()  # Controlador de Voo
    COREOGRAFO = auto()  # Coreografo
    CORRETOR_EM_GERAL = auto()  # Corretor em Geral
    CORTADOR = auto()  # Cortador
    COSTUREIRA = auto()  # Costureira/Bordadeira/Cerzideira
    COZINHEIRO_CONFEITEIRO_PADEIRO = auto()  # Cozinheiro/Confeiteiro/Padeiro
    DECORADOR = auto()  # Decorador
    DEGUSTADOR_VINHO_CAFE = auto()  # Degustador(Vinho/Café etc)
    DELEGADO_DE_POLICIA = auto()  # Delegado de Policia
    DEMONSTRADOR = auto()  # Demonstrador
    DENTISTA_ODONTOLOGO = auto()  # Dentista/Odontologo
    DEPILADOR = auto()  # Depilador
    DEPUTADO_ESTADUAL_FEDERAL = auto()  # Deputado Estadual/Federal
    DESEMBARGADOR = auto()  # Desembargador
    DESENHISTA = auto()  # Desenhista
    DESPACHANTE_INCLUSIVE_ADUANEIRO = auto()  # Despachante (inclusive aduaneiro)
    DETETIVE_INVESTIGADOR = auto()  # Detetive/Investigador
    DETETIZADOR = auto()  # Detetizador
    DIGITADOR = auto()  # Digitador
    DIPLOMATA = auto()  # Diplomata
    DIRETOR_DE_EMPRESA = auto()  # Diretor de Empresa
    DIRETOR_DE_ESPETACULOS = auto()  # Diretor de Espetaculos
    DIRETOR_DE_ESTABELECIMENTO_DE_ENSINO = auto()  # Diretor de Estabelecimento de Ensino
    ECONOMISTA = auto()  # Economista
    ELETRICISTA = auto()  # Eletricista
    EMBALADOR = auto()  # Embalador
    EMBALSAMADOR = auto()  # Embalsamador
    EMPREGADA_DOMESTICA = auto()  # Empregada domestica
    EMPRESARIO_DE_ATLETA = auto()  # Empresario de Atleta
    ENFERMEIRO = auto()  # Enfermeiro
    ENGENHEIRO = auto()  # Engenheiro
    ENTREVISTADOR_CENSO_PESQUISA_PRECOS = auto()  # Entrevistador(Censo/Pesquisa/Preços)
    ESCRITOR = auto()  # Escritor
    ESCULTOR = auto()  # Escultor
    ESOTERICOS_ASTROLOGOS_TAROLOGO_NUMEROLOGO = auto()  # Esotericos(Astrologos/Tarologo/Numerologo etc)
    ESTATISTICO = auto()  # Estatistico
    ESTETICISTA = auto()  # Esteticista
    ESTILISTA_MODELISTA = auto()  # Estilista/Modelista
    ESTIVADOR = auto()  # Estivador
    FARMACEUTICO = auto()  # Farmaceutico
    FAXINEIRO_DIARISTA = auto()  # Faxineiro/Diarista
    FEIRANTE = auto()  # Feirante
    FERRAMENTEIRO = auto()  # Ferramenteiro
    FISCAL = auto()  # Fiscal
    FISCAL_DE_PRODUCAO = auto()  # Fiscal de Producao
    FISCAL_SERVICOS_DE_TRANSPORTE = auto()  # Fiscal Serviços de Transporte
    FISICO = auto()  # Fisico
    FISIOTERAPEUTA = auto()  # Fisioterapeuta
    FOGUISTA_DE_EMBARCACOES_OU_LOCOMOTIVAS = auto()  # Foguista de Embarcacoes ou Locomotivas
    FONOAUDIOLOGO = auto()  # Fonoaudiologo
    FORCAS_ARMADAS_SOLDADO_MARINHEIRO = auto()  # Forças Armadas (Soldado,Marinheiro,etc)
    FOTOGRAFO = auto()  # Fotografo
    FRENTISTA_TRABALHADOR_DE_POSTO_DE_GASOLINA = auto()  # Frentista/Trabalhador de posto de gasolina
    FUNCIONARIO_PUBLICO_CIVIL_APOSENTADO = auto()  # Funcionario Publico Civil Aposentado
    FUNDIDOR = auto()  # Fundidor
    GARAGISTA = auto()  # Garagista
    GARCOM_MAITRE = auto()  # Garçom/Maitre
    GARIMPEIRO = auto()  # Garimpeiro
    GEOGRAFO = auto()  # Geografo
    GEOLOGO = auto()  # Geologo
    GERENTE = auto()  # Gerente
    GESSISTA = auto()  # Gessista
    GOVERNADOR_DE_ESTADO = auto()  # Governador de Estado
    GOVERNANTA = auto()  # Governanta
    GUIA_TURISTICO = auto()  # Guia Turistico
    HOSPITAL_TRABALHADORES_EM_GERAL = auto()  # Hospital - Trabalhadores em Geral
    IMPERMEABILIZADOR = auto()  # Impermeabilizador
    INSPETOR = auto()  # Inspetor
    INSPETOR_DE_CONTROLE_DE_QUALIDADE = auto()  # Inspetor de Controle de Qualidade
    INSTALADOR_DE_GAS_AGUA_ESGOTO = auto()  # Instalador de Gas,Agua e Esgoto
    INSTRUMENTADOR_CIRURGICO = auto()  # Instrumentador Cirurgico
    INSTRUMENTISTA = auto()  # Instrumentista
    INSTRUTOR_DE_AUTOESCOLA = auto()  # Instrutor de Autoescola
    INSTRUTOR_PROFESSOR_CURSOS_LIVRES = auto()  # Instrutor/Professor de Cursos Livres(Ginastica,Ingles,Informatica)
    INTERPRETE_TRADUTOR = auto()  # Interprete/Tradutor
    JARDINEIRO = auto()  # Jardineiro
    JOALHEIRO = auto()  # Joalheiro
    JORNALEIRO = auto()  # Jornaleiro
    JORNALISTA_REPORTER = auto()  # Jornalista/Reporter
    JUIZ_DE_DIREITO = auto()  # Juiz de Direito
    LANTERNEIRO = auto()  # Lanterneiro
    LAVADOR_DE_CARROS_ROUPAS = auto()  # Lavador de Carros/Roupas
    LEILOEIRO = auto()  # Leiloeiro
    LEITURISTA = auto()  # Leiturista
    GARI = auto()  # Lixeiro/Gari/Varredor/Coletor de Lixo
    LOCUTOR = auto()  # Locutor
    MANICURE_PEDICURE_PODOLOGO = auto()  # Manicure/Pedicure/Podologo
    MANOBRISTA_NAO_EMPREGADO_GUARDADOR_DE_CARRO = auto()  # Manobrista (não empregado)/Guardador de Carro
    MAQUILADOR = auto()  # Maquilador
    MAQUINISTA_DE_EMBARCACOES_OU_LOCOMOTIVAS = auto()  # Maquinista de Embarcacoes ou Locomotivas
    MARCENEIRO_CARPINTEIRO = auto()  # Marceneiro/Carpinteiro
    MARINHEIRO_ASS = auto()  # Marinheiro e Ass.
    MASSAGISTA = auto()  # Massagista
    MATEMATICO = auto()  # Matematico
    MECANICO = auto()  # Mecanico
    MEDICO = auto()  # Medico
    MEMBRO_DA_DEFENSORIA_PUBLICA = auto()  # Membro da Defensoria Publica
    MEMBRO_DE_EQUIPE_TECNICA_DE_ESPORTES = auto()  # Membro de Equipe tecnica de esportes
    MEMBRO_DO_MINISTERIO_PUBLICO = auto()  # Membro do Ministerio Publico
    MEMBRO_EQUIPE_TECNICA_ESPORTES = auto()  # Membro Equipe Técnica Esportes
    MESTRE_DE_PRODUCAO = auto()  # Mestre de Producao
    METEOROLOGISTA = auto()  # Meteorologista
    MILITAR_EM_GERAL = auto()  # Militar em Geral
    MILITAR_REFORMADO = auto()  # Militar reformado
    MINISTRO_DE_ESTADO = auto()  # Ministro de Estado
    MINISTRO_DE_TRIBUNAL_SUPERIOR = auto()  # Ministro de Tribunal Superior
    MODELO_DE_MODAS = auto()  # Modelo de Modas
    MONTADOR = auto()  # Montador
    MOTORISTA_TRANSPORTE_CARGAS = auto()  # Motorista (veiculo transporte cargas)
    MOTORISTA_TRANSPORTE_DE_PASSAGEIROS = auto()  # Motorista (veiculo transporte de passageiros)
    MOTORISTA_AUTONOMO_TAXISTA_PRINCIPAL = auto()  # Motorista autonomo (taxista principal)
    MUSEOLOGO = auto()  # Museologo
    MUSICO = auto()  # Musico
    NUTRICIONISTA = auto()  # Nutricionista
    OFFICE_BOY_CONTINUO_ENTREGADOR_MOTOBOY = auto()  # Office boy/Continuo/Entregador/Motoboy
    OFICIAL_DE_FORCAS_AUX_FORCAS_ARMADAS = auto()  # Oficial de Forças Aux e Forças Armadas
    OFICIAL_DE_JUSTICA = auto()  # Oficial de Justiça
    OPERADOR_DE_CALDEIRA = auto()  # Operador de Caldeira
    OPERADOR_DE_CAMERAS_DE_CINEMA_TV = auto()  # Operador de Cameras de Cinema e TV
    OPERADOR_DE_COMPUTADOR = auto()  # Operador de Computador
    OPERADOR_DE_GUINDASTE = auto()  # Operador de Guindaste
    OPERADOR_DE_ILUMINACAO = auto()  # Operador de Iluminacao
    OPERADOR_DE_MAQUINAS_APARELHOS = auto()  # Operador de Maquinas e Aparelhos
    OPERADOR_DE_TELEMARKETING = auto()  # Operador de Telemarketing
    OPERARIO_SEMI_ESPECIALIZADO_PRODUCAO = auto()  # Operario Semi-especializado Producao
    ORIENTADOR_PEDAGOGICO = auto()  # Orientador Pedagogico
    OURIVES = auto()  # Ourives
    PAISAGISTA = auto()  # Paisagista
    PEDREIRO = auto()  # Pedreiro
    PENSAO_ALIMENTICIA_PARA_FILHOS = auto()  # Pensao alimenticia para filhos
    PENSIONISTA = auto()  # Pensionista
    PERSONAL_TRAINER = auto()  # Personal Trainer
    PESCADOR = auto()  # Pescador
    PESQUISADOR_CIENTIFICO = auto()  # Pesquisador Cientifico
    PILOTO_DE_AERONAVES = auto()  # Piloto de Aeronaves
    PINTOR = auto()  # Pintor
    PISCICULTOR = auto()  # Piscicultor
    PORTEIRO_ZELADOR = auto()  # Porteiro/Zelador
    PORTUARIO = auto()  # Portuario
    PREFEITO = auto()  # Prefeito
    PRENSISTA_ESTAMPADOR = auto()  # Prensista/Estampador
    PROCURADOR_MEMBROS_DA_PROCURADORIA = auto()  # Procurador/Membros da Procuradoria
    PRODUTOR_DE_EVENTOS = auto()  # Produtor de Eventos(Promoter)/Produtor de Artes em geral
    PROFESSOR_AUTONOMO_PARTICULAR = auto()  # Professor Autonomo/Particular
    PROFESSOR_ENSINO_FUNDAMENTAL_E_MEDIO = auto()  # Professor de Ensino Fundamental e Medio
    PROFESSOR_ENSINO_SUPERIOR = auto()  # Professor de Ensino Superior
    PROFESSOR_IDIOMAS = auto()  # Professor de Idiomas
    PROFISSIONAL_CIRCO_ACROBATA = auto()  # Profissional de Circo/Acrobata
    PROFISSIONAL_LETRAS_ARTES = auto()  # Profissional de Letras e Artes
    PROGRAMADOR = auto()  # Programador
    PROMOTOR_DE_VENDAS = auto()  # Promotor de Vendas
    PROMOTOR_PUBLICO = auto()  # Promotor Publico
    PROPRIETARIO_COMERCIAL = auto()  # Proprietario de Estabel. Comercial
    PROPRIETARIO_INDUSTRIAL = auto()  # Proprietario de Estabel. Industrial
    PROPRIETARIO_MICROEMPRESA = auto()  # Proprietario de Microempresa
    PROPRIETARIO_PRESTACAO_SERVICOS = auto()  # Proprietario de Estabel. de Prestaçao Serviços
    PROPRIETARIO_RURAL_AGRICOLA_FLORESTAL_PECUARI = auto()  # Proprietario de Estabel. Rural,Agricola,Florestal,Pecuario
    PROTETICO = auto()  # Protetico
    PSICANALISTA = auto()  # Psicologo/Terapeuta/Psicanalista
    PSICOTERAPEUTA = auto()  # Psicologo/Terapeuta/Psicoterapeuta
    PUBLICITARIO = auto()  # Publicitario
    QUIMICO = auto()  # Quimico
    RADIALISTA = auto()  # Radialista
    RECEPCIONISTA = auto()  # Recepcionista
    RECICLAGEM = auto()  # Reciclagem - Trabalhadores em geral
    RECREADOR = auto()  # Recreador
    RELACOES_PUBLICAS = auto()  # Relacoes Publicas
    RELOJOEIRO = auto()  # Relojoeiro
    REPRESENTANTE_COMERCIAL = auto()  # Representante Comercial
    SAPATEIRO = auto()  # Sapateiro
    SECRETARIA = auto()  # Secretaria
    SECRETARIO_DE_ESTADO = auto()  # Secretario de Estado
    SECRETARIO_MUNICIPAL = auto()  # Secretario Municipal
    SECURITARIO = auto()  # Securitario
    SEGURANCA_PATRIMONIAL = auto()  # Segurança Patrimonial - trabalhadores em geral
    SENADOR = auto()  # Senador
    SERRALHEIRO = auto()  # Serralheiro
    SERVENTUARIO_DA_JUSTICA = auto()  # Serventuario da Justiça
    SERVICOS_DE_MANUTENCAO = auto()  # Serviços de Manutencao
    SOCIOLOGO = auto()  # Sociologo
    SOLDADO_CORPO_DE_BOMBEIROS = auto()  # Soldado Corpo de Bombeiros
    SUPERINTENDENTE = auto()  # Superintendente
    SUPERVISOR = auto()  # Supervisor
    SUPERVISOR_TECNICO_OPERACIONAL = auto()  # Supervisor/Tecnico Operacional
    TABELIAO = auto()  # Tabeliao
    TAPECEIRO = auto()  # Tapeceiro
    TECNICO_DA_RECEITA_FEDERAL = auto()  # Tecnico da Receita Federal
    TECNICO_DE_BIOLOGIA = auto()  # Tecnico de Biologia
    TECNICO_DE_CONTABILIDADE = auto()  # Tecnico de Contabilidade
    TECNICO_DE_ELETRICIDADE = auto()  # Tecnico de Eletricidade
    TECNICO_DE_ELETRONICA = auto()  # Tecnico de Eletronica
    TECNICO_DE_ESTATISTICA = auto()  # Tecnico de Estatistica
    TECNICO_DE_LABORATORIO = auto()  # Tecnico de Laboratorio
    TECNICO_DE_MECANICA = auto()  # Tecnico de Mecanica
    TECNICO_DE_QUIMICA = auto()  # Tecnico de Quimica
    TECNICO_DE_RADIOLOGIA = auto()  # Tecnico de Radiologia
    TECNICO_DE_TELECOMUNICACOES = auto()  # Tecnico de Telecomunicacoes
    TECNICO_EM_AGRONOMIA = auto()  # Tecnico em Agronomia
    TECNICO_EM_DESPORTOS = auto()  # Tecnico em Desportos
    TECNICO_EM_EDIFICACOES = auto()  # Tecnico em Edificacoes
    TECNICO_EM_ELETRONICA = auto()  # Tecnico em Eletronica
    TECNICO_EM_ESTATISTICA = auto()  # Tecnico em Estatistica
    TECNICO_EM_FARMACIA = auto()  # Tecnico em Farmacia
    TECNICO_EM_FINANCAS = auto()  # Tecnico em Finanças
    TECNICO_EM_INFORMATICA = auto()  # Tecnico em Informatica
    TECNICO_EM_INSEMINACAO = auto()  # Tecnico em Inseminacao
    TECNICO_EM_MECANICA = auto()  # Tecnico em Mecanica
    TECNICO_EM_QUIMICA = auto()  # Tecnico em Quimica
    TECNICO_EM_RADIOLOGIA = auto()  # Tecnico em Radiologia
    TECNICO_EM_REFRIGERACAO = auto()  # Tecnico em Refrigeracao
    TECNICO_EM_TELECOMUNICACOES = auto()  # Tecnico em Telecomunicacoes
    TECNICO_PROJETISTA = auto()  # Tecnico Projetista
    TELEFONISTA = auto()  # Telefonista
    TERAPEUTA_OCUPACIONAL = auto()  # Terapeuta Ocupacional
    TORNEIRO = auto()  # Torneiro
    TRABALHADOR_DA_ADMINISTRACAO = auto()  # Trabalhador da Administracao
    TRABALHADOR_DA_PESCA = auto()  # Trabalhador da Pesca
    TRABALHADOR_DE_ARTES_GRAFICAS = auto()  # Trabalhador de Artes Graficas
    TRABALHADOR_DE_CONSTRUCAO_CIVIL = auto()  # Trabalhador de Construcao Civil
    TRABALHADOR_FABRICACAO_FUMO_CIGARRO_CHARUTOS = auto()  # Trabalhador Fabricacao fumo/cigarro/charutos
    TRABALHADOR_FABRICACAO_FUMO_CIGARROS_CHARUTOS = auto()  # Trabalhador Fabricacao fumo/cigarros/charutos
    TRABALHADOR_INDUSTRIAL = auto()  # Trabalhador Industrial
    TRABALHADOR_RURAL = auto()  # Trabalhador Rural
    TRABALHADOR_SERV_CONTABCAIXA_ASS = auto()  # Trabalhador serv. contab.caixa e ass.
    TRAINEES = auto()  # Trainees
    VENDEDOR = auto()  # Vendedor
    VENDEDOR_PRACISTA = auto()  # Vendedor Pracista
    VEREADOR = auto()  # Vereador
    VETERINARIO = auto()  # Veterinario
    VIDRACEIRO = auto()  # Vidraceiro
    WEBDESIGNER = auto()  # Webdesigner
    ZOOTECNISTA = auto()  # Zootecnista
