from enum import Flag, auto


class State(Flag):
    AC = auto()
    AL = auto()
    AP = auto()
    AM = auto()
    BA = auto()
    CE = auto()
    DF = auto()
    ES = auto()
    GO = auto()
    MA = auto()
    MT = auto()
    MS = auto()
    MG = auto()
    PA = auto()
    PB = auto()
    PR = auto()
    PE = auto()
    PI = auto()
    RJ = auto()
    RN = auto()
    RS = auto()
    RO = auto()
    RR = auto()
    SC = auto()
    SP = auto()
    SE = auto()
    TO = auto()
